### ISSUE TITLE
[Bug]: 1.20.4 fabric crash

### ISSUE THREAD

**Issue by EfficientStinkbug** [someaddons/SavageEnderDragon#52]
### Describe the bug you're experiencing

destroyed end crystal

### Reproducability

Time: 2024-05-17 17:39:04
Description: Exception ticking world

java.lang.IllegalAccessError: class com.dragonfight.fight.DragonFightManagerCustom tried to access private method 'void net.minecraft.class_1324.method_6202(net.minecraft.class_1322)' (com.dragonfight.fight.DragonFightManagerCustom and net.minecraft.class_1324 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @55040f2f)
	at com.dragonfight.fight.DragonFightManagerCustom.setDragonHealth(DragonFightManagerCustom.java:371)
	at com.dragonfight.fight.DragonFightManagerCustom.onWorldTick(DragonFightManagerCustom.java:244)
	at com.dragonfight.event.EventHandler.onWorldTick(EventHandler.java:19)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63)
	at net.minecraft.class_3218.handler$cdl000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:7274)
	at net.minecraft.class_3218.method_18765(class_3218.java:410)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.4

### Modloader version

Fabric

### Logs

Time: 2024-05-17 17:39:04 Description: Exception ticking world  java.lang.IllegalAccessError: class com.dragonfight.fight.DragonFightManagerCustom tried to access private method 'void net.minecraft.class_1324.method_6202(net.minecraft.class_1322)' (com.dragonfight.fight.DragonFightManagerCustom and net.minecraft.class_1324 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @55040f2f) 	at com.dragonfight.fight.DragonFightManagerCustom.setDragonHealth(DragonFightManagerCustom.java:371) 	at com.dragonfight.fight.DragonFightManagerCustom.onWorldTick(DragonFightManagerCustom.java:244) 	at com.dragonfight.event.EventHandler.onWorldTick(EventHandler.java:19) 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63) 	at net.minecraft.class_3218.handler$cdl000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:7274) 	at net.minecraft.class_3218.method_18765(class_3218.java:410) 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948) 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845) 	at net.minecraft.class_1132.method_3748(class_1132.java:110) 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) 	at java.base/java.lang.Thread.run(Thread.java:833)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------

**Comment by someaddons** [comment]
ye the mod is for 20.1 :D
